FROM ubuntu:24.04
ENV container docker
ENV PATH "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
ENV LC_ALL C.UTF-8

RUN apt update
RUN apt install -y libopenblas0 libgomp1 libgflags2.2 curl git make gcc zlib1g-dev libbz2-dev libzstd-dev  g++ libsnappy-dev liblz4-dev

RUN --mount=type=bind,source=build/mnt,target=/mnt,rw \
    bash --login /mnt/build.sh release ci

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
