process:
  logfile: /usr/local/faissdb/log/faissdb.log
  pidfile: /usr/local/faissdb/tmp/faissdb.pid
  daemon: false
http:
  port: 9093
  maxconnections: 1000
  httptimeout: 60
db:
  dbpath: /usr/local/faissdb/data
  faiss:
    dimension: 2
    syncinterval: 60000
    description: IVF2,PQ2_8
    metric: InnerProduct
    nprobe: 10
  metadb:
    capacity: 1073741824
  datadb:
    capacity: 1073741824
  iddb:
    capacity: 1073741824
  logdb:
    capacity: 1073741824
oplog:
  term: 3600
feature:
  listen: ":20023"
replica:
  listen: ":21023"
