name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        test_script:
          - test.sh
    container:
      image: crumbjp/faissdb@sha256:3b4e0d150e4e9f090e9d5e2046e83d194d485fddfd6217fd10205cf35a2c469a
    steps:
      - uses: actions/checkout@v2

      - name: run ${{ matrix.test_script }}
        run: bash ${{ matrix.test_script }}
