name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: faissdb

      - uses: actions/checkout@v4
        with:
          repository: crumbjp/go-faiss
          path: go-faiss

      - name: Run CI
        working-directory: faissdb
        run: bash ci/run.sh
